# Generated by Django 4.1.1 on 2023-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='view',
            field=models.CharField(blank=True, choices=[('ops', 'OPS'), ('noc', 'NOC'), ('telefonica', 'TELEFONICA'), ('correos', 'CORREOS'), ('indefinida_1', 'INDEFINIDA 1'), ('indefinida_2', 'INDEFINIDA 2'), ('indefinida_3', 'INDEFINIDA 3')], max_length=65535, null=True, verbose_name='Vistas'),
        ),
    ]
